connector_image: airbyte/source-databricks:dev
tests:
  spec:
    - spec_path: "source_databricks/spec.json"
  connection:
    - config_path: "integration_tests/sample_config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "integration_tests/sample_config.json"
  basic_read:
    - config_path: "integration_tests/sample_config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      validate_output_from_all_streams: false
      empty_streams: []
      expect_records: true
      expected_records: []
      timeout_seconds: 60
